name: Run MATLAB tests on dev branch
on:
  # Trigger the workflow on push or pull request,
  # but only for the dev branch
  push:
    branches:
      - dev
      - github_actions_windows
  pull_request:
    branches:
      - dev
concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  run_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        release: [R2020b, R2021a, R2021b, latest]
        os: [ubuntu-latest, windows-latest]
    name: MATLAB ${{ matrix.release }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Check out LFS objects
        run: git lfs checkout
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v2-beta
        with:
          release: ${{ matrix.release }}
          products: Simulink Simscape Simscape_Multibody
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: test java env
        run: echo $JAVA_HOME
        shell: bash
      - name: Install WEC-Sim
        uses: matlab-actions/run-command@v1
        with:
          command: |
            addpath(genpath('source')),
            savepath pathdef.m;
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-command@v1
        with:
          command: |
            set_param(0, 'ErrorIfLoadNewModel', 'off'),
            results = wecSimTest,
            assertSuccess(results);
